version: "3.9"

services:
  backend:
    image: himansh2k3/fusionpact-backend:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: himansh2k3/fusionpact-frontend:latest
    container_name: static-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge